name: Build PrusaSlicer Debian

on:
  schedule:
    # Check for upstream changes daily at 10 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Manual trigger
    inputs:
      force_build:
        description: 'Force build even if no new release'
        required: false
        default: 'false'
        type: boolean
      target_version:
        description: 'Specific version to build (e.g., version_2.7.1). Leave empty for latest.'
        required: false
        default: ''
        type: string
  
jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      has-new-release: ${{ steps.check.outputs.has-new-release }}
      latest-tag: ${{ steps.check.outputs.latest-tag }}
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check for new upstream releases
        id: check
        run: |
          # Add upstream remote
          git remote add upstream https://github.com/prusa3d/PrusaSlicer.git
          git fetch upstream --tags
          
          # Determine target version
          if [ "${{ github.event.inputs.target_version }}" != "" ]; then
            LATEST_TAG="${{ github.event.inputs.target_version }}"
            echo "Using specified version: $LATEST_TAG"
          else
            # Get latest upstream tag
            LATEST_TAG=$(git ls-remote --tags upstream | grep -E 'refs/tags/version_[0-9]' | sort -V | tail -1 | sed 's/.*refs\/tags\///')
            echo "Latest upstream tag: $LATEST_TAG"
          fi
          
          # Check if we have this tag locally
          if git tag -l | grep -q "^$LATEST_TAG$"; then
            echo "Tag $LATEST_TAG already exists locally"
            echo "has-new-release=false" >> $GITHUB_OUTPUT
          else
            echo "New tag found: $LATEST_TAG"
            echo "has-new-release=true" >> $GITHUB_OUTPUT
          fi
          
          # Determine if we should build
          if [ "${{ github.event.inputs.force_build }}" == "true" ]; then
            echo "Force build requested"
            echo "should-build=true" >> $GITHUB_OUTPUT
          elif git tag -l | grep -q "^$LATEST_TAG$"; then
            echo "should-build=false" >> $GITHUB_OUTPUT
          else
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi
          
          echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT

  build-debian:
    needs: check-upstream
    # if: needs.check-upstream.outputs.should-build == 'true'  # Temporarily disabled for testing
    runs-on: ubuntu-latest
    container: debian:bookworm
    
    steps:
      - name: Install git and basic tools
        run: |
          apt-get update
          apt-get install -y git ca-certificates curl
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Sync with upstream
        run: |
          git config --global --add safe.directory /__w/$(echo ${{ github.repository }} | cut -d'/' -f2)/$(echo ${{ github.repository }} | cut -d'/' -f2)
          git remote add upstream https://github.com/prusa3d/PrusaSlicer.git
          git fetch upstream --tags
          
          # Check if tag exists
          if git tag -l | grep -q "^${{ needs.check-upstream.outputs.latest-tag }}$"; then
            echo "Tag exists, checking out..."
            git checkout ${{ needs.check-upstream.outputs.latest-tag }}
          else
            echo "Tag not found locally, trying to fetch..."
            git fetch upstream ${{ needs.check-upstream.outputs.latest-tag }}:${{ needs.check-upstream.outputs.latest-tag }}
            git checkout ${{ needs.check-upstream.outputs.latest-tag }}
          fi
          
      - name: Install build dependencies
        timeout-minutes: 15
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential cmake git \
            libgl1-mesa-dev libglu1-mesa-dev \
            libgtk-3-dev libgtk2.0-dev \
            pkg-config gettext curl wget \
            ca-certificates libssl-dev \
            perl
            
      - name: Build dependencies using PrusaSlicer deps script
        timeout-minutes: 90
        run: |
          echo "=== Building PrusaSlicer dependencies ==="
          cd deps
          
          # Debug: Check what files contain bintray URLs
          echo "=== Checking for bintray URLs ==="
          grep -r "bintray.com" . || echo "No bintray URLs found"
          
          # Fix Boost download URL in all cmake files
          echo "=== Fixing Boost download URLs ==="
          find . -name "*.cmake" -exec grep -l "bintray.com" {} \; | while read file; do
            echo "Fixing $file"
            sed -i 's|https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz|https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download|g' "$file"
            echo "After fix:"
            grep -n "boost_1_66_0" "$file" || echo "No boost URLs found"
          done
          
          # Fix OpenSSL build - disable problematic features
          echo "=== Fixing OpenSSL build issues ==="
          if [ -f "deps-unix-common.cmake" ]; then
            # Add --no-tests flag to OpenSSL configure to avoid 'make depend' issues
            sed -i 's|CONFIGURE_COMMAND ./config|CONFIGURE_COMMAND ./config no-tests|g' deps-unix-common.cmake
            # Alternative: skip OpenSSL entirely and use system version
            echo "OpenSSL fixes applied"
          fi
          
          mkdir build
          cd build
          
          # Configure with relaxed compiler warnings for gtest compatibility
          export CXXFLAGS="-Wno-maybe-uninitialized"
          export CFLAGS="-Wno-maybe-uninitialized"
          
          cmake .. -DDEP_WX_GTK3=ON
          
          echo "=== Starting make with verbose output ==="
          make -j$(nproc) VERBOSE=1 || {
            echo "=== Build failed, trying single-threaded ==="
            make -j1 || {
              echo "=== Single-threaded failed, trying without OpenSSL ==="
              cd ..
              cmake . -DDEP_WX_GTK3=ON -DDEP_OPENSSL=OFF
              make -j1
            }
          }
          echo "=== Dependencies build completed ==="
          
      - name: Build PrusaSlicer with static dependencies
        timeout-minutes: 60
        run: |
          echo "=== Building PrusaSlicer ==="
          mkdir build
          cd build
          cmake .. \
            -DSLIC3R_STATIC=1 \
            -DSLIC3R_GTK=3 \
            -DSLIC3R_PCH=OFF \
            -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local
          make -j$(nproc)
          echo "=== PrusaSlicer build completed ==="
          
      - name: Find and prepare binary
        run: |
          find build -name "prusa-slicer" -type f -executable
          mkdir -p dist
          find build -name "prusa-slicer" -type f -executable -exec cp {} dist/ \;
          ls -la dist/
          
      - name: Create AppImage
        run: |
          echo "=== Creating AppImage ==="
          cd dist
          
          # Create AppDir structure
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps
          mkdir -p AppDir/usr/share/pixmaps
          
          # Copy binary
          cp prusa-slicer AppDir/usr/bin/
          
          # Create desktop file
          cat > AppDir/usr/share/applications/prusa-slicer.desktop << 'EOF'
          [Desktop Entry]
          Name=PrusaSlicer
          Comment=G-code generator for 3D printers
          Exec=prusa-slicer
          Icon=prusa-slicer
          Type=Application
          Categories=Graphics;3DGraphics;Engineering;
          MimeType=application/sla;model/stl;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;application/x-amf;
          EOF
          
          # Try to find and copy icon from source
          if [ -f "../../resources/icons/PrusaSlicer.png" ]; then
            cp ../../resources/icons/PrusaSlicer.png AppDir/usr/share/icons/hicolor/128x128/apps/prusa-slicer.png
            cp ../../resources/icons/PrusaSlicer.png AppDir/usr/share/pixmaps/prusa-slicer.png
          else
            # Create a simple placeholder icon
            echo "Creating placeholder icon..."
            # This would be a basic text-based icon - you'd want a real PNG
          fi
          
          # Download and use linuxdeploy to create AppImage
          echo "Downloading linuxdeploy..."
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          
          echo "Creating AppImage..."
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage --executable AppDir/usr/bin/prusa-slicer
          
          # Rename to include version
          if ls *.AppImage 1> /dev/null 2>&1; then
            for appimage in *.AppImage; do
              mv "$appimage" "PrusaSlicer-${{ needs.check-upstream.outputs.latest-tag }}-x86_64.AppImage"
            done
          fi
          
          ls -la *.AppImage || echo "No AppImage created"
          
      - name: Test binary
        run: |
          cd dist
          ./prusa-slicer --help || echo "Binary test completed"
          
      - name: Upload Debian Build (Binary)
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer-Debian-Binary-${{ needs.check-upstream.outputs.latest-tag }}
          path: dist/prusa-slicer
          retention-days: 90
          
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer-Debian-AppImage-${{ needs.check-upstream.outputs.latest-tag }}
          path: dist/*.AppImage
          retention-days: 90
          
      - name: Create build info
        run: |
          echo "PrusaSlicer ${{ needs.check-upstream.outputs.latest-tag }}" > dist/BUILD_INFO
          echo "Built on Debian Bookworm with static dependencies" >> dist/BUILD_INFO
          echo "Build date: $(date)" >> dist/BUILD_INFO
          echo "Built using official PrusaSlicer deps script" >> dist/BUILD_INFO
          
      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer-Debian-BuildInfo-${{ needs.check-upstream.outputs.latest-tag }}
          path: dist/BUILD_INFO
          retention-days: 90

  tag-local:
    needs: [check-upstream, build-debian]
    if: needs.check-upstream.outputs.has-new-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Tag and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ needs.check-upstream.outputs.latest-tag }}
          git push origin ${{ needs.check-upstream.outputs.latest-tag }}
