# .github/workflows/sync-upstream.yml
name: Sync Upstream
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync upstream changes
        run: |
          git remote add upstream https://github.com/prusa3d/PrusaSlicer.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push
